### ISSUE TITLE
Copy project markers and regions in time selection

### ISSUE THREAD

**Issue by MusicVI** [cfillion/reascripts#3]
Hi Cfillion!

We are using your custom script "Script: cfillion_Copy project markers and regions in time selection.lua" in a custom action, but I need the script to skip if there are no project markers or regions in the time selection. Is there a way to modify the script to do this? At the moment the script gives an error which breaks the custom action when there are no project markers or regions. Thanks in advance! Love your work :)

**Comment by cfillion** [comment]
Version 1.1.2 will be up soon with the message box removed.

**Comment by MusicVI** [comment]
Ok thanks for the reply!
