### ISSUE TITLE
Action: Apply render preset not saving Directory 

### ISSUE THREAD

**Issue by alucast** [cfillion/reascripts#4]
Would be cool if possible to load also the preset's output directory. Currently it doesn't for me at least. 
This so we can immediately use the action "File: Render project, using the most recent render settings, with a new target file name..." 

thanks!

**Comment by dt3989** [comment]
Same problem

**Comment by cfillion** [comment]
I've looked into it today: while I can read the directory from the preset file since v6.43, it seems that ReaScripts cannot change it.

**Comment by cfillion** [comment]
Version v2.1.1 added support for this.
