### ISSUE TITLE
Toggle track FX bypass by name doesn't work with master track.

### ISSUE THREAD

**Issue by garubi** [cfillion/reascripts#5]
I'll use the "Toggle track FX bypass by name" script on the Master track, but I can't target that track.
I tried "Master" but it's ignored.

Is it something you could change/implement?

My use case is the following:
I have a room correctio plugin on the Master track and I constantly forget to disable it before rendering.
I would like to build a custom action, including your script, to disable that plugin before rendering.

Thak you

**Comment by cfillion** [comment]
Good idea, done!

**Comment by garubi** [comment]
Great!
Thank you.
I'll go testing it ;-)

**Comment by garubi** [comment]
I found a little issue with the popup labels.
The track name field's label is truncated.

![image](https://github.com/cfillion/reascripts/assets/10868669/392bb567-184e-463a-9607-aa1b266c1cf5)
