### ISSUE TITLE
Toggle track FX bypass by name doesn't work with monitor FX.

### ISSUE THREAD

**Issue by garubi** [cfillion/reascripts#6]
Since you addressed issue #5 so quickly...
I would be useful if one can address the monitor FX, too... 

Thank you

Stefano

**Comment by cfillion** [comment]
Released version 2.0 with a new UI (fixing the truncated label) and an option to search in the monitor or input FX chain:

![Version 2.0](https://github.com/cfillion/reascripts/assets/4297676/7366cabe-9e87-4df4-9d88-71cb25fc8a63)

**Comment by garubi** [comment]
Great! thank you.
I'll try it in the next few days
