### ISSUE TITLE
Error in line 271: "missing closing quote"

### ISSUE THREAD

**Issue by Linguista** [cfillion/reascripts#7]
Hi. I'm trying to use the scripts `Script: cfillion_Apply render preset.lua` and `Script: cfillion_Apply render preset (create action).lua` in Reaper 7.15 on Win 11, and they both throw the same error:

`cfillion_Apply render preset.lua:271: missing closing quote`
`cfillion_Apply render preset (create action).lua:271: missing closing quote`

I've tried reinstalling the scripts using ReaPack, uninstalling and installing them the same way, and editing them and pasting the text from this repo into the script file, and I get the same error every time. I've manually confirmed that they've been deleted in the first two cases, too.

**Comment by Linguista** [comment]
Just FYI, I downgraded to the previous version (2.1.2) of the scripts and the same problem occurs, except on line 276.

**Comment by cfillion** [comment]
Can you share your reaper-render.ini and reaper-render2.ini files? The error occurs because there's something unexpected in those.

**Comment by Linguista** [comment]
Sure. Please find them attached. I've redacted various personal details
from reaper-render2, but I've only changed letters -- punctuation and such
remains untouched.

**Comment by cfillion** [comment]
> Please find them attached

I don't see any attachments – GitHub does not read them from emails. Files may only be added when replying using the website.

**Comment by Linguista** [comment]
Sorry about that! Here are the files.
[reaper-render.ini.txt](https://github.com/cfillion/reascripts/files/15314838/reaper-render.ini.txt)
[reaper-render2--REDACTED.ini.txt](https://github.com/cfillion/reascripts/files/15314839/reaper-render2--REDACTED.ini.txt)

**Comment by cfillion** [comment]
Thanks! It was the quotes in the `TAG APE:Album 'Score of "Film Name", a film by DIRECTOR'` line in reaper-render2.ini.

Released version 2.1.4 with the fix.

**Comment by Linguista** [comment]
Wow! Amazing speed! It's now working. Thanks to much.
